helm:
  parameters:
  - name: global.gateway.address
    value: server-gateway-svc.aqua
    forcestring: false
  - name: global.gateway.port
    value: "8443"
    forcestring: false
  - name: platform
    value: k8s
    forcestring: false
  - name: image.tag
    value: 2022.4.114
    forcestring: true
  - name: image.name
    value: registry.aquasec.com/enforcer
    forcestring: true
