apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aqua-enforcer
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: aqua
  source:
    repoURL: 'https://helm.aquasec.com/'
    chart: enforcer
    targetRevision: 2022.4.5
    helm:
      parameters:
        - name: gate.host
          value: aqua-lb
        - name: gate.port
          value: '443'
        - name: platform
          value: k8s
        - name: image.tag
          value: 2022.4.71
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: aqua
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
