apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aqua-kube-enforcer
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: aqua
  source:
    repoURL: 'https://helm.aquasec.com/'
    chart: kube-enforcer
    targetRevision: 2022.4.4
    helm:
      parameters:
        - name: certsSecret.autoGenerate
          value: 'true'
        - name: gateway.address
          value: aqua-lb
        - name: global.gateway.port
          value: '443'
        - name: starboard.OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT
          value: '2'
        - name: serviceAccount.create
          value: 'true'
        - name: serviceAccount.name
          value: 'aqua-sa'
        - name: image.tag
          value: '2022.4.71'

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: aqua
  syncPolicy:
    automated:
      prune: true
      selfHeal: true