global:
  connectServerUrl: https://connect.codesec.aquasec.com
  scanServerUrl: https://scan.codesec.aquasec.com
  aquaServerUrl: https://api.aquasec.com
  cspmServerUrl: https://api.cloudsploit.com

credentials:
  aqua_key:
  aqua_secret:

# SCM configurations:
integration:
  # Should be one of: github|gitlab_server|azure|jenkins|etc...
  source:
  url:
  username:
  password:

# Optionally add ssl ca cert and client cert/key for ssl connection to the SCM/CI server:
ssl:
  enabled: false
#  ca: |
#    -----BEGIN CERTIFICATE-----
#    ca-cert
#    -----END CERTIFICATE
#  cert: |
#    -----BEGIN CERTIFICATE-----
#    client-cert
#    -----END CERTIFICATE-----
#  key: |
#    -----BEGIN RSA PRIVATE KEY-----
#    secure key
#    -----BEGIN RSA PRIVATE KEY-----

# Proxy configurations:
proxy:
  # The proxy url to redirect requests to.
  url:
  # Proxy redirection preference
  # Allowed values: inbound|outbound|both
  # inbound: redirect only inbound requests through the proxy
  # Description: requests to the integration only, requests to Aqua Security servers will not be proxied
  # outbound: redirect only outbound requests through the proxy
  # Description: requests to Aqua Security servers only, requests to the integration will not be proxied
  # both: redirect both inbound and outbound requests through the proxy
  # Description: requests to Aqua Security servers and requests to the integration will be proxied
  preference: outbound

connect:
  image: docker.io/aquasec/codesec-connector:minified
  pullPolicy: Always
  port: 9999
  client_url:
  service:
    port: 9999
    type: ClusterIP
    annotations: {}
  resources: {}
  nodeSelector: {}
  affinity: {}
  tolerations: {}
  hostAliases:
  extraEnv: {}

scan:
  image: docker.io/aquasec/codesec-scanner:latest
  pullPolicy: Always
  replicas: 1
  resources: {}
  nodeSelector: {}
  affinity: {}
  tolerations: {}
  hostAliases:
  extraEnv: {}
